### ISSUE TITLE
Is it for SQuAD2.0?

### ISSUE THREAD

**Issue by littleforce163** [Z3376/BiDAF-SQuAD2.0#1]
Hi Guys,
I see the code shows as below:
train_df = pd.read_json('./gdrive/My Drive/squad**1.1**_train-v2.0.json')
Is it for SQuAD2.0?

**Comment by Z3376** [comment]
Hi there.
Yeah, it's for SQuAD2.0 only. The file was renamed, you can ignore that.

**Comment by littleforce163** [comment]
Thanks
